### ISSUE TITLE
Certificates are expired

### ISSUE THREAD

**Issue by askucher** [zhangyuanwei/node-siri#15]
I got this error 

```
Error: ACE:Unknow ACE package type"7".
    at SiriParser.StreamParser.onError (/var/www/node-siri/parser.js:40:11)
    at PackageParser.packageParser.onError (/var/www/node-siri/parser.js:227:14)
    at PackageParser.execute (/var/www/node-siri/parser.js:382:26)
    at Fifo.callback (/var/www/node-siri/parser.js:16:21)
    at Fifo.push (/var/www/node-siri/fifo.js:44:22)
    at PackageParser.StreamParser.parse (/var/www/node-siri/parser.js:29:15)
    at Unzip.<anonymous> (/var/www/node-siri/parser.js:215:23)
    at emitOne (events.js:90:13)
    at Unzip.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
```

Do you have cert generation script?

**Comment by askucher** [comment]
I see "Undefined error: Error: certificate has expired"

**Comment by askucher** [comment]
Found genca.sh
