### ISSUE TITLE
Error: ACE:Unknow ACE package type"7".

### ISSUE THREAD

**Issue by askucher** [zhangyuanwei/node-siri#16]
```
Error: ACE:Unknow ACE package type"7".
    at SiriParser.StreamParser.onError (/var/www/node-siri/parser.js:40:11)
    at PackageParser.packageParser.onError (/var/www/node-siri/parser.js:227:14)
    at PackageParser.execute (/var/www/node-siri/parser.js:383:26)
    at Fifo.callback (/var/www/node-siri/parser.js:16:21)
    at Fifo.push (/var/www/node-siri/fifo.js:44:22)
    at PackageParser.StreamParser.parse (/var/www/node-siri/parser.js:29:15)
    at Unzip.<anonymous> (/var/www/node-siri/parser.js:215:23)
    at emitOne (events.js:90:13)
    at Unzip.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
```

but dns, certs are correct!

**Comment by askucher** [comment]
Debug info

```
root@raspberrypi:/var/www/node-siri# pwd
/var/www/node-siri
root@raspberrypi:/var/www/node-siri# ls -la
total 156
drwxr-xr-x 10 root root  4096 May  1 00:37 .
drwxr-xr-x  6 root root  4096 May  1 00:22 ..
drwxr-xr-x  8 root root  4096 Apr 30 23:47 .git
-rw-r--r--  1 root root   128 Apr 30 23:47 .gitignore
-rw-r--r--  1 root root  1079 Apr 30 23:47 LICENSE
-rw-r--r--  1 root root  4667 Apr 30 23:47 README.md
-rw-r--r--  1 root root  1157 Apr 30 23:47 README.zh_CN.md
drwxr-xr-x  2 root root  4096 Apr 30 23:47 bin
-rw-r--r--  1 root root 26001 Apr 30 23:47 bplist.js
-rw-r--r--  1 root root   119 Apr 30 23:48 config.json
-rw-r--r--  1 root root   118 Apr 30 23:47 config.json.sample
drwxr-xr-x  2 root root  4096 May  1 08:58 contrib
drwxr-xr-x  2 root root  4096 Apr 30 23:47 data
drwxr-xr-x  4 root root  4096 Apr 30 23:47 examples
-rw-r--r--  1 root root  2029 Apr 30 23:47 fifo.js
-rw-r--r--  1 root root    21 May  1 00:37 install
-rw-r--r--  1 root root  2769 Apr 30 23:47 install.html
-rw-r--r--  1 root root  4137 Apr 30 23:47 install.js
drwxr-xr-x  3 root root  4096 May  1 08:58 keys
drwxr-xr-x  2 root root  4096 Apr 30 23:47 locales
drwxr-xr-x 62 root root  4096 Apr 30 23:47 node_modules
-rw-r--r--  1 root root  1109 Apr 30 23:47 package.json
-rw-r--r--  1 root root 11700 May  1 00:52 parser.js
-rwxr-xr-x  1 root root    69 May  1 00:42 run
-rw-r--r--  1 root root 16632 Apr 30 23:47 siri.js
root@raspberrypi:/var/www/node-siri# cat config.json
{
    "locale": "en",
    "server": "guzzoni.apple.com",
    "port": 443,
    "dumpdata":false,
    "dnsproxy":false
}
root@raspberrypi:/var/www/node-siri# cat examples/proxy.js
var siri = require("../siri");

siri.createServer(function(cmd, dev) {
    console.log(cmd);
    dev.proxy();
}).start();
root@raspberrypi:/var/www/node-siri# openssl x509 -in keys/server-cert.pem -noout -text
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            dc:dd:86:69:e6:04:a9:9d
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=Some-State, O=Internet Widgits Pty Ltd, CN=guzzoni.apple.com
        Validity
            Not Before: May  1 08:57:58 2016 GMT
            Not After : May  1 08:57:58 2018 GMT
        Subject: C=US, ST=Some-State, O=Internet Widgits Pty Ltd, CN=guzzoni.apple.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (1024 bit)
                Modulus:
                    00:c9:6e:bc:b3:88:81:67:22:80:64:56:67:2f:85:
                    23:6f:1d:6c:d8:65:c4:13:be:e0:a7:ae:ec:50:8c:
                    d0:33:f6:56:9c:dc:6a:64:ea:31:f6:d4:b5:d8:91:
                    49:54:2b:5c:83:cc:ae:7a:09:72:73:31:14:55:47:
                    f7:57:c7:7e:a1:e5:c7:2e:56:08:d8:38:a4:9d:c9:
                    db:70:ce:6a:08:97:6a:12:ec:75:df:c2:d6:88:28:
                    9a:ed:68:51:ea:d1:78:b5:c9:71:c4:5e:ac:18:f3:
                    67:0a:7d:6a:45:07:78:6d:1f:a7:aa:cd:8c:b5:d5:
                    8a:dc:21:8a:95:0b:5c:e2:2d
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
         65:d1:da:3d:42:f8:5b:b7:c8:5f:ae:d0:75:16:25:18:d7:83:
         10:4d:c0:d6:02:a9:5d:b2:f0:80:bb:e4:8b:5a:f7:a7:c2:f4:
         a5:bc:9a:54:6e:d3:d2:d9:ed:38:77:7c:b0:93:33:4e:76:b4:
         ab:97:10:91:74:d5:26:75:42:d3:f2:0d:df:ee:ca:73:cd:e6:
         98:11:86:b4:17:32:1b:c5:eb:c8:78:08:60:c8:cc:bd:29:17:
         a2:9a:7c:6e:ea:35:1c:36:63:be:e7:a6:e7:b5:ce:0f:33:4f:
         f1:51:73:2a:7e:ad:c6:55:ea:77:aa:64:f9:83:15:43:09:7d:
         91:48
root@raspberrypi:/var/www/node-siri# nslookup guzzoni.apple.com
Server:         192.168.1.1
Address:        192.168.1.1#53

Name:   guzzoni.apple.com
Address: 192.168.1.120

root@raspberrypi:/var/www/node-siri# node -v
v5.10.1
```

**Comment by askucher** [comment]
More

```
root@raspberrypi:/var/www/node-siri# sudo DEBUG=siri:* node examples/en-US/hello.js --dumpdata true                                                                                                                                                                                                       
  siri:debug Siri Proxy version 1.1.1 +0ms
  siri:debug Siri Proxy starting on port 443 +14ms
  siri:debug Client connected. +4s
  siri:debug Client connected. +55ms
Undefined error: Error: self signed certificate
  siri:debug Server disconnected. +17ms
  siri:debug Client disconnected. +16ms
  siri:warn Error: socket hang up
    at TLSSocket.<anonymous> (_tls_wrap.js:829:25)
    at emitOne (events.js:95:20)
    at TLSSocket.emit (events.js:182:7)
    at Socket.<anonymous> (net.js:475:12)
    at Socket.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:475:12) +24ms
[ERROR] ECONNRESET :: The connection has been forcefully terminated.
  siri:debug Server disconnected. +16ms
  siri:debug Recycling resources. +1ms
  siri:debug Client disconnected. +7ms
  siri:debug Recycling resources. +1ms
  siri:debug Client connected. +241ms
  siri:debug Client connected. +43ms
Undefined error: Error: self signed certificate
  siri:debug Server disconnected. +13ms
  siri:debug Client disconnected. +3ms
  siri:debug Client disconnected. +12ms
  siri:debug Recycling resources. +1ms
  siri:warn Error: socket hang up
    at TLSSocket.<anonymous> (_tls_wrap.js:829:25)
    at emitOne (events.js:95:20)
    at TLSSocket.emit (events.js:182:7)
    at Socket.<anonymous> (net.js:475:12)
    at Socket.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:475:12) +10ms
[ERROR] ECONNRESET :: The connection has been forcefully terminated.
  siri:debug Client connected. +12ms
  siri:debug Server disconnected. +3ms
  siri:debug Recycling resources. +2ms
  siri:debug Client connected. +35ms
  siri:debug Client connected. +7ms
Undefined error: Error: self signed certificate
  siri:debug Server disconnected. +5ms
  siri:debug Client disconnected. +4ms
  siri:debug Client disconnected. +11ms
  siri:debug Recycling resources. +0ms
  siri:debug Client connected. +33ms
  siri:warn Error: socket hang up
    at TLSSocket.<anonymous> (_tls_wrap.js:829:25)
    at emitOne (events.js:95:20)
    at TLSSocket.emit (events.js:182:7)
    at Socket.<anonymous> (net.js:475:12)
    at Socket.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:475:12) +9ms
[ERROR] ECONNRESET :: The connection has been forcefully terminated.
Undefined error: Error: self signed certificate
  siri:debug Server disconnected. +7ms
  siri:debug Server disconnected. +2ms
  siri:debug Recycling resources. +1ms
  siri:debug Client disconnected. +6ms
  siri:debug Client connected. +23ms
  siri:debug Client disconnected. +10ms
  siri:debug Recycling resources. +1ms
  siri:warn Error: socket hang up
    at TLSSocket.<anonymous> (_tls_wrap.js:829:25)
    at emitOne (events.js:95:20)
    at TLSSocket.emit (events.js:182:7)
    at Socket.<anonymous> (net.js:475:12)
    at Socket.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:475:12) +1ms
[ERROR] ECONNRESET :: The connection has been forcefully terminated.
  siri:debug Server disconnected. +17ms
  siri:debug Recycling resources. +1ms
  siri:debug Client connected. +24ms
  siri:debug Client connected. +7ms
Undefined error: Error: self signed certificate
  siri:debug Server disconnected. +5ms
  siri:debug Client disconnected. +5ms
  siri:debug Client disconnected. +36ms
  siri:debug Recycling resources. +0ms
  siri:warn Error: socket hang up
    at TLSSocket.<anonymous> (_tls_wrap.js:829:25)
    at emitOne (events.js:95:20)
    at TLSSocket.emit (events.js:182:7)
    at Socket.<anonymous> (net.js:475:12)
    at Socket.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:475:12) +3ms
[ERROR] ECONNRESET :: The connection has been forcefully terminated.
  siri:debug Client connected. +12ms
  siri:debug Server disconnected. +10ms
  siri:debug Recycling resources. +1ms
Undefined error: Error: self signed certificate
  siri:debug Server disconnected. +3ms
  siri:debug Client disconnected. +4ms
  siri:debug Client disconnected. +18ms
  siri:debug Recycling resources. +1ms
  siri:warn Error: socket hang up
    at TLSSocket.<anonymous> (_tls_wrap.js:829:25)
    at emitOne (events.js:95:20)
    at TLSSocket.emit (events.js:182:7)
    at Socket.<anonymous> (net.js:475:12)
    at Socket.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:475:12) +1ms
[ERROR] ECONNRESET :: The connection has been forcefully terminated.
  siri:debug Client connected. +11ms
  siri:debug Server disconnected. +1ms
  siri:debug Recycling resources. +1ms
  siri:debug Client connected. +30ms
Undefined error: Error: self signed certificate
  siri:debug Server disconnected. +3ms
  siri:debug Client disconnected. +3ms
  siri:debug Client disconnected. +20ms
  siri:debug Recycling resources. +1ms
  siri:warn Error: socket hang up
    at TLSSocket.<anonymous> (_tls_wrap.js:829:25)
    at emitOne (events.js:95:20)
    at TLSSocket.emit (events.js:182:7)
    at Socket.<anonymous> (net.js:475:12)
    at Socket.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:475:12) +1ms
[ERROR] ECONNRESET :: The connection has been forcefully terminated.
  siri:debug Server disconnected. +6ms
  siri:debug Recycling resources. +1ms
```

**Comment by hems** [comment]
Did you manage to solve this?
